const IMAGES = {    
    image1 : new URL('./img_cer/cer_html.png', import.meta.url).href,
    image2 : new URL('./img_cer/cer_css.png', import.meta.url).href,
    image3 : new URL('./img_cer/cer_js.png', import.meta.url).href,
    image4 : new URL('./img_cer/cer_api.png', import.meta.url).href,
    image5 : new URL('./img_cer/cer_react_appchat.png', import.meta.url).href,
    image6 : new URL('./img_cer/cer_react_port.png', import.meta.url).href,
    image7 : new URL('./img_cer/1_react_port.png', import.meta.url).href,
    image8 : new URL('./img_cer/2_react_port.png', import.meta.url).href,
    image9 : new URL('./img_cer/3_react_port.png', import.meta.url).href,
    image10 : new URL('./img_cer/img_cer/1_react_appchat.png', import.meta.url).href,
    image11 : new URL('./img_design/Logo fitness app.png', import.meta.url).href,
    image12 : new URL('./img_design/Menu.png', import.meta.url).href,
    image13 : new URL('./img_design/Run.png', import.meta.url).href,
    image14 : new URL('./img_design/page 1.png', import.meta.url).href,
    image15 : new URL('./img_design/page 2.png', import.meta.url).href,
    image16 : new URL('./img_design/page 4.png', import.meta.url).href,
    image17 : new URL('./img_design/food_menu.png', import.meta.url).href,
    image18 : new URL('./img_design/cart.png', import.meta.url).href,
    image19 : new URL('./img_design/customer.png', import.meta.url).href,
    image20 : new URL('./img_design/logo_bakery.png', import.meta.url).href,
    image21 : new URL('./img_design/logo_app.png', import.meta.url).href,
    image22 : new URL('./img_design/logo_page.png', import.meta.url).href,
    image23 : new URL('./img_design/logo_shirt.png', import.meta.url).href,
}

export default IMAGES
